# Generated by Django 4.2.1 on 2023-05-05 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chanakya', '0004_career'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='post',
        ),
    ]
