# Generated by Django 4.2.1 on 2023-05-05 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chanakya', '0005_remove_career_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Career',
        ),
    ]
