# Generated by Django 4.2.1 on 2023-05-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chanakya', '0007_career'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='post',
            field=models.CharField(choices=[('select', 'SELECT'), ('prt', 'PRT'), ('tgt', 'TGT'), ('other', 'OTHER')], default='SELECT', max_length=20),
        ),
    ]
