# Generated by Django 4.2.1 on 2023-05-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chanakya', '0009_delete_career'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.TextField(max_length=10)),
                ('post', models.CharField(choices=[('select', 'SELECT'), ('prt', 'PRT'), ('tgt', 'TGT'), ('other', 'OTHER')], default='SELECT', max_length=20)),
                ('resume', models.ImageField(upload_to='files/')),
            ],
        ),
    ]
