# Generated by Django 4.2.1 on 2023-05-05 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chanakya', '0010_career'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='resume',
        ),
    ]
