# Generated by Django 4.2.1 on 2023-05-05 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chanakya', '0011_remove_career_resume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Career',
        ),
    ]
