# Generated by Django 4.2.1 on 2023-05-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chanakya', '0013_career'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.TextField(max_length=10)),
                ('LastName', models.TextField(max_length=10)),
                ('LastSchool', models.TextField(max_length=30)),
                ('FatherName', models.TextField(max_length=10)),
                ('phone', models.TextField(max_length=10)),
                ('Address', models.TextField(max_length=50)),
                ('SiblingName', models.TextField(max_length=20)),
                ('Class', models.TextField(max_length=10)),
            ],
        ),
    ]
